### ISSUE TITLE
保存ROI的坐标在原图无缩放的情况下

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#103]
在保存记录的时候，每一条记录增加长方形的坐标点。左上，和右下两个坐标（x，y；x，y）。这种格式未来我们增加到多坐标（freehand）的时候，也能适用。

如果原图有缩放，这个坐标需要是把原图恢复成原始状态后的记录。我们不要记录原图的缩放比例，减轻未来英国那边的二次开发成本

**Comment by cyokin** [comment]
Add coordinate on both **roi_history** and **roi_image** table. 
**Example:**   
{"x": 765.1526315789474, "y": 389.30526315789473, "width": 641.8578947368421, "height": 373.5105263157895}
**No crop** if the coordinate value is {"x": 0, "y": 0, "width": 0, "height": 0}
