### ISSUE TITLE
机器品牌增加“声科”/“Supersonic”及“日立”/“Hitachi”

### ISSUE THREAD

**Issue by grantmakesplane** [cyokin/ten-d-acd#104]
机器品牌增加“声科”/“Supersonic”及“日立”/“Hitachi”

**Comment by cyokin** [comment]
run below TSQL script for add machine into DB 
insert into public.machine_type(machine_type_id, machine_type_name,machine_type_chinese_name)
values   (7,'Supersonic','声科'),   (8,'Hitachi','日立')
