### ISSUE TITLE
每一个Client需要增加一个过期管理办法

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#107]
商用之后，我们会根据合同，把每一个client变成一个只能在某一段时间有效的软件。如果合同过期，医院没有续约，需要能够停止。这个mechanism需要（certificate或者是什么）。

**Comment by wdcn** [comment]
解决办法：
- 所有的Client在某个文件夹下有一个证书文件。包含开始时间和过期时间。

**Comment by cyokin** [comment]
这个需要增加以下功能。 
**Admin端**
- 医院管理
- 医院证书管理(发放，下载) 。
- 证书加密，医院ID和证书绑定，采用公钥和私钥机制。
**客户端**
- 证书过期页面
- 证书服务器端和客户端过期验证。
- 证书揭秘，过期时间判断。
