### ISSUE TITLE
Add Buckingham logo to the about page

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#11]
Add the logo to the about page and add "TenD Innovations & The University of Buckingham Computer Vision Lab"

![image](https://user-images.githubusercontent.com/7055516/52300868-d84a4280-293d-11e9-8f22-869e4682dd2b.png)

**Comment by cyokin** [comment]
where i can get logo  file @wdcn

**Comment by wdcn** [comment]
The logo has been sent to your hotmail
