### ISSUE TITLE
Admin - 图片下载

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#112]
按照和client一样的下载方式，但是！！！！

- 在最后的GUID的结尾加上用户名的GUID
- 在下载的csv文件中加上坐标

**Comment by cyokin** [comment]
admin 0.0.3 released
数据库用户ID是Int类型的， 所以图片名最后加 <图片>_<用户ID>.png  
Example: Thyroidnodules_Samsung__Benign_0fad761f-ca82-4ac7-9c5b-6252b59f5db0_1.png
