### ISSUE TITLE
生成一个分支版本，在该版本下将诊断结果改为风险等级

### ISSUE THREAD

**Issue by grantmakesplane** [cyokin/ten-d-acd#118]
恶性的为90%的可能性时，风险等级显示为“★★★★☆”。
恶性的为80%的可能性时，风险等级显示为“★★★★”。

具体风险划分标准参考如下：

恶性50% ~ 60%：  ★★☆
恶性60% ~ 70%：  ★★★
恶性70% ~ 80%：  ★★★☆
恶性70% ~ 80%：  ★★★★
恶性80% ~ 90%：  ★★★★☆
恶性90% ~ 100%：★★★★★

良性50% ~ 60%：  ★★☆
良性60% ~ 70%：  ★★
良性70% ~ 80%：  ★☆
良性70% ~ 80%：  ★
良性80% ~ 90%：  ☆
良性90% ~ 100%：

*注：50% ~ 60% 表示为“**大于**百分之五十，并且**小于等于**百分之六十”，以此类推。

**Comment by cyokin** [comment]
最高都是5颗星，就是说可能性最大。永远显示5颗星，没到的就是空白的星。即如下
良性90% ~ 100%：无星
良性80% ~ 90%： 半星
良性70% ~ 80%： 1颗半星
良性60% ~ 70%： 2颗星
良性50% ~ 60%： 2颗半星
恶性50% ~ 60%： 2颗半星
恶性60% ~ 70%： 3颗星
恶性70% ~ 80%： 3颗半星
恶性70% ~ 80%： 4颗星
恶性80% ~ 90%： 4颗半星，还有半星空白
恶性90% ~ 100%：5颗星
这是基于我们的结果不会有恶性 0- 50% 和 良性0-50%的情况。

**Comment by cyokin** [comment]
cut
