### ISSUE TITLE
About page - statistics

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#13]
Implement the statistics table on the about page

**Comment by cyokin** [comment]
UI Please @wdcn

**Comment by cyokin** [comment]
@wdcn never mind, i found it from previous spec 
2.	A table to show the diagnostics information
a.	Cancer type
b.	Number of diagnostics conducted in the version
c.	Lowest process time 
d.	Fastest process time
e.	Avergae process time

**Comment by cyokin** [comment]
done

**Comment by cyokin** [comment]
make sure run view.sql before check this ticket

**Comment by wdcn** [comment]
Verified
