### ISSUE TITLE
版本1.9.0问题汇总

### ISSUE THREAD

**Issue by grantmakesplane** [cyokin/ten-d-acd#130]
版本：1.9.0
图像模型：Version 0.0.4 UoB Testing

1, 中文翻译问题：uniform == “均质化”，ratio == “纵横比”，irregularity == “不规则程度”。建议把wider改为wide。

2, 显示问题：

- 在ROI块，Echos后面的“低，中，高”的占比建议用饼状图显示出来，这样更加直观。

- 在Calcification块，建议将Calcification标题下的Calcification改为“有钙化”或者“无钙化”。

3, 切图问题：在切完一张图并进行分析后，点击其它的选项再返回首页会导致无法正常切新的图像。
例如：导入图像，切图并分析。点击listview，返回home页面。导入新的图像，点击pen。无法切图。

**Comment by apex10000** [comment]
1、ROI：uniform/not uniform == '均质‘/’不均质‘，Echo三个数字分别为low/medium/high ’低/中/高回声‘比例
Shape: Taller than Wide/Wider than Tall; Ratio == '纵横比'
Calcification:  Calcification/No Calcification == '有钙化/无钙化’  Index == ‘钙化比例’ 
Margin:  Irregularity =='不规则度' 
以上除纵横比外其它所有数值结果建议用进度条/饼图等视觉化方式呈现，以直观显示数值高低程度

2、后续增加数据记录存储及查询列表功能，目前list view/import menu不可用需隐藏

3、此版本为甲状腺Certification专用版本，中文下拉菜单名称‘Cancer Type/癌症类型’改为‘Organ/器官’，此版本只有一个value=“Thyroid/甲状腺”； "Machine Type/B超机器类型"改为“Machine Brand/超声设备品牌”

**Comment by wdcn** [comment]
已经修复
