### ISSUE TITLE
显示及翻译问题

### ISSUE THREAD

**Issue by apex10000** [cyokin/ten-d-acd#132]
ROI：uniform/not uniform == '均质‘/’不均质‘，Echo三个数字分别为low/medium/high ’低/中/高回声‘比例
Shape: Taller than Wide/Wider than Tall; Ratio == '纵横比'
Calcification: Calcification/No Calcification == '有钙化/无钙化’ Index == ‘钙化比例’
Margin: Irregularity =='不规则度'
以上除纵横比外其它所有数值结果建议用进度条/饼图等视觉化方式呈现，以直观显示数值高低程度

**Comment by wdcn** [comment]
除了饼图之外都已经修复完毕。饼图是一个新的功能点，加上会比较花。而且也不是现在的重点，建议挪后处理。
