### ISSUE TITLE
其它目录菜单内容修改

### ISSUE THREAD

**Issue by apex10000** [cyokin/ten-d-acd#133]
增加数据记录存储及查询列表功能，如目前list view/import menu不可用，可先隐藏

目前1.9.0版本为甲状腺Certification专用版本，中文下拉菜单名称‘Cancer Type/癌症类型’改为‘Organ/器官’，此版本只有一个value=“Thyroid/甲状腺”； "Machine Type/B超机器类型"改为“Machine Brand/超声设备品牌”

**Comment by wdcn** [comment]
fixed
