### ISSUE TITLE
Localization support - Language toggle

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#14]
Adding a language toggle on top of page to support Chinese
- The default language is based upon user's OS setting
- User can use the language toggle to change the whole system's text

**Comment by cyokin** [comment]
@wdcn 你先翻译，根据en.js， 翻译到cn.js 保持相同格式。 
https://github.com/cyokin/ten-d-acd/tree/master/frontend/src/lang

**Comment by wdcn** [comment]
1. Title of the software won't change to Chinese
2. Cancer type, Machine type won't change to Chinese

**Comment by cyokin** [comment]
Title of the software in master.title,  I have updated accordingly 
Cancer type, Machine type those string are changed to Chinese, but the value of those type are not UI data, those are in DB. usually we are not changing them.

**Comment by cyokin** [comment]
@wdcn 
uploading latest version into onedriver
