### ISSUE TITLE
System update: jar file update

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#21]
ML model and site code update mechanism

**Comment by cyokin** [comment]
check architecture from following url
https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&page-id=TSgiEl2F1_Tro3ljHiVb&title=tend-architecture.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fcyokin%2Fworkflow%2Fmaster%2Ftend-architecture.xml
