### ISSUE TITLE
Add a new filter "Prediction" to the list

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#28]
We need to add a new filter to allow users to filter the "Prediction" filter values. This use case comes from the image download feature - University might want to do "Pathology = M" & "Prediction = B", so they can get all those inaccurate predictions to re-train the model

**Comment by cyokin** [comment]
@wdcn 
the value of prediction is vary, how do we make a filter on that? search input text box will be make it complex. 
"chain mail","leopard","sandbar","velvet","lakeside". there are a lot in the DB now. all come from the detector.

**Comment by wdcn** [comment]
in the latest model, the prediction will be restricted to the same B/M. So we can follow the same

**Comment by cyokin** [comment]
Please make sure Alaa's JAR only response "Malignant" or "Benign", nothing else. 👍

**Comment by cyokin** [comment]
done
