### ISSUE TITLE
软件分割以符合软件著作权标准

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#30]
根据下面的软件著作权来把代码分割成如下的不同类库

1、用户操作程序，即通过导入一张或者多张B超影片，并选择肿瘤类别；
2、系统标注出重点影片区域(ROI: Region of Interests)的程序；
3、自动判断该区域的组织属于良性组织还是恶性组织的程序；
4、判定的准确几率程序；
5、操作及各项显示的程序；
6、历史纪录B超原片和影片区域影片的加密程序；
7、数据管理程序。

**Comment by cyokin** [comment]
1、用户操作程序，即通过导入一张或者多张B超影片，并选择肿瘤类别；
   frontend UI home page
2、系统标注出重点影片区域(ROI: Region of Interests)的程序；
   frontend UI home page with cropperjs
3、自动判断该区域的组织属于良性组织还是恶性组织的程序；
   Cancer_Img_Recognition Class built by Matlab
4、判定的准确几率程序；
   Cancer_Img_Recognition Class built by Matlab
5、操作及各项显示的程序；
   frontend UI
6、历史纪录B超原片和影片区域影片的加密程序；
   we don't have any encryption now. 	
7、数据管理程序。
   backend RecordService
