### ISSUE TITLE
about page

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#39]
1. add Tend logo - http://www.tendenergies.com/images/tenDlogo_verticle_whitetext.png
2. "Powered by Ten-D Innovation's J-Eye Cancer Diagnosis Engine, and under the licensing agreement with the University of Buckingham"

**Comment by cyokin** [comment]
where is logo file

**Comment by wdcn** [comment]
Added the logo to the request

**Comment by cyokin** [comment]
done
