### ISSUE TITLE
内存使用优化

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#48]
1. The way of loading the JAR File, and keep it in the memory. 
3. The UI modules loaded in the warmup, and not deleted from the memory.
2. the idea of loading two AI models and keep them in the memory to improve the performance of the system.
3.  loading the images into the memory (check Hongbo’s comments). 
4. The limitation of the RAM. But 8GB RAM should be fine!

**Comment by cyokin** [comment]
There is no any big backend code change between 0.0.3 and 0.0.4 version.  I don;t see any code will impact the performance except the image_recognition.jar.  as it increase the size from 800MB to 1.2 GB.
