### ISSUE TITLE
Localization: Database value localization 

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#54]
There are some values stored in the DB that requires to be localized as well

1. Cancer Type
2. Machine type
3. Predication
4. Pathology

**Comment by cyokin** [comment]
@wdcn 
1，2 翻译在 https://github.com/cyokin/ten-d-acd/blob/master/db/data.sql 
3，4 翻译在 https://github.com/cyokin/ten-d-acd/blob/master/frontend/src/lang/cn.js

**Comment by wdcn** [comment]
@cyokin 这不是都翻译好了么？还有我要翻译都东西么？有些像什么TN那些about页面都专业词汇是故意不翻译的

**Comment by cyokin** [comment]
check out detail for https://github.com/cyokin/ten-d-acd/wiki/0.0.5-to-0.0.6
