### ISSUE TITLE
两台服务器的架构

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#62]
我们部署商用的时候，会有两台服务器，部署在医院内网。然后一台主服务器，一台是failover的，医院内网到时候我们根据医院付钱买的license开几个网站访问的权限。

1. 访问机器数量控制
2. failover的时候转到另外服务器
3. 两台服务器的备份同步

**Comment by cyokin** [comment]
你这是架构，还是实现啊，图片同步比较麻烦的，除非存到数据库。

**Comment by cyokin** [comment]
还有这个还要和docker一起架构的。

**Comment by cyokin** [comment]
我觉得这个有点overkill, 现在企业都做云备份。感觉比2台服务器更加安全，并且收费更合理。
@wdcn
