### ISSUE TITLE
Responsive: 首页

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#65]
4列view：100%: 我们现在的样式
3列view: 75%: 现在的样式
2列view：50%：修复以下bug - 1. title问题通过另外的按钮变成收起的方式解决。2. 检测结果bug修复，另外去掉检测的用时会帮助
1列view：25%：这个还是用50%加上横向scrollbar
![image](https://user-images.githubusercontent.com/7055516/54869520-e241cc80-4d56-11e9-9dbf-abe4e0aacda1.png)

**Comment by wdcn** [comment]
那个结果和导出按钮还是有点问题。上面都好了。
![image](https://user-images.githubusercontent.com/7055516/55051208-63c48380-5011-11e9-8b6e-b278595d518e.png)

**Comment by cyokin** [comment]
- download latest jar for test
- you may need delete local docker image in order to test new version, we they share save version number.  
you can run following command to delete docker image "docker rmi cyokin/tend:0.0.8"
