### ISSUE TITLE
Home - save button 

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#7]
![image](https://user-images.githubusercontent.com/7055516/52039833-6f506e00-24ea-11e9-939f-a41822b64a7b.png)

1. Change the Save button label to "Save record" so the button is longer and more prominent
2. If the button is not enabled and user clicks on it, poup an alert box saying "Please complete all information before saving"

**Comment by cyokin** [comment]
you can;t add event on disabled button :(
