### ISSUE TITLE
数据下载程序

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#73]
在某个医院里面，维护人员通过此程序把数据库和图片下载到U盘中

1. 数据库备份：全库备份
2. 图片备份：全库备份

**Comment by cyokin** [comment]
- latest code at  
https://github.com/cyokin/ten-d-acd/blob/master/bin/com.tend.acd.exporter-0.0.1-SNAPSHOT.jar 
- how to use it at  
https://github.com/cyokin/ten-d-acd/tree/master/exporter
