### ISSUE TITLE
数据上传程序

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#74]
在每个医院的数据备份到U盘之后，把U盘带回主服务器，利用此程序把数据库和图片文件夹同步到主数据库中。

- 做增量不做同步

**Comment by cyokin** [comment]
- latest code at  
https://github.com/cyokin/ten-d-acd/blob/master/bin/com.tend.acd.exporter-0.0.1-SNAPSHOT.jar 
- how to use it at  
https://github.com/cyokin/ten-d-acd/tree/master/exporter

**Comment by cyokin** [comment]
上传比较麻烦，需要到服务器上，然后上传，不然会有安全隐患的。
