### ISSUE TITLE
分离about page，加版本统计

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#78]
1. 用户端的about page，去掉统计的table，保留版本和鸣谢等信息
2. Admin portal里面增加一个统计页面，显示此table
3. Admin portal里面的统计增加一个可以根据AI/UI版本信息filter的统计

**Comment by cyokin** [comment]
#3 这个需要详细讨论一下，你指的是AI版本吧？ 不是UI版本
