### ISSUE TITLE
程序切图即保存

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#82]
- 切图的时候保存原图，roi图，prediction在一个表里面

**Comment by cyokin** [comment]
after cut image, you verify the results by call http://localhost:3000/api/db/v_roi_history API
or query DB directly with "SELECT * from v_roi_history "

**Comment by cyokin** [comment]
check wiki for https://github.com/cyokin/ten-d-acd/wiki/0.0.9-to-0.0.10
