### ISSUE TITLE
BVT for build verification

### ISSUE THREAD

**Issue by wdcn** [cyokin/ten-d-acd#85]
在每次的build产出的时候，需要跑BVT把20个B和20个M的数据核实成功。

这个和 https://github.com/cyokin/ten-d-acd/issues/95 应该可以是一套接口

**Comment by cyokin** [comment]
add unit test case for BVT build, it will run this unit test case for each release,  
but I have M case, for the B case you given it wrong, i need roi image not original image, this will make result to M. 
Please provide 10 B case with ROI image
