### ISSUE TITLE
新装的机器无法在“关于我们”页面显示统计数据

### ISSUE THREAD

**Issue by grantmakesplane** [cyokin/ten-d-acd#90]
新装的机器在运行 com.tend.acd.backend-0.0.12-SNAPSHOT.jar 时无法在“关于我们”页面正常显示统计数据。降级到com.tend.acd.backend-0.0.11-SNAPSHOT.jar 后，可以正常显示统计数据。

**Comment by wdcn** [comment]
这个是故意的
